# Configuración de logging para debugging
logging:
  level:
    root: INFO
  "com.kafka.producer": DEBUG
  "org.springframework.kafka": INFO
  "org.apache.kafka": WARN
  "org.springframework.retry": INFO

# Configuración personalizada de Kafka (Producer)
kafka:
  server: localhost:9092  # Opción A (WSL2 estable)
  producer:
    topic: visit-request-topic
    acks: all
    retries: 3

# Datasource MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kafka?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      fetch-size: 100
      max-rows: 1000

# Scheduler
scheduler:
  enabled: true
  # Consulta por defecto; se puede sobrescribir por env o perfil
  query: |
    SELECT
      dataclient.*,
      TIMESTAMPDIFF(HOUR, dataclient.created_datetime, NOW()) AS hours_elapsed,
      CONCAT(
        FLOOR(TIMESTAMPDIFF(MINUTE, dataclient.created_datetime, NOW()) / 1440), 'd ',
        MOD(FLOOR(TIMESTAMPDIFF(MINUTE, dataclient.created_datetime, NOW()) / 60), 24), 'h ',
        MOD(TIMESTAMPDIFF(MINUTE, dataclient.created_datetime, NOW()), 60), 'm'
      ) AS age_elapsed
    FROM clients dataclient
    WHERE 
    dataclient.status = 'pending'
    AND dataclient.created_datetime <= NOW() - INTERVAL 72 HOUR;
  # Cron por defecto: cada hora al minuto 0
  cron: 0 */2 * * * *

# Actuator
management:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
